# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-slim

WORKDIR /app

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev

ENTRYPOINT ["node", "dist/index.js"]
